export const transferData = [
    {
        date: "2024-10-01",
        transactionId: "TRX1001",
        sender: "Alice Marie Carter",
        beneficiary: "Robert James Williams",
        amount: "$500.00",
        transferType: "Internal",
        status: "Completed",
    },
    {
        date: "2024-10-02",
        transactionId: "TRX1002",
        sender: "Elijah Thomas Green",
        beneficiary: "Sophia Grace Lee",
        amount: "$200.00",
        transferType: "External",
        status: "Completed",
    },
    {
        date: "2024-10-03",
        transactionId: "TRX1003",
        sender: "Emma Rose Thompson",
        beneficiary: "Lucas Henry Martin",
        amount: "$750.00",
        transferType: "Internal",
        status: "Pending",
    },
    {
        date: "2024-10-04",
        transactionId: "TRX1004",
        sender: "Mason David Brown",
        beneficiary: "Olivia Claire Garcia",
        amount: "$1,200.00",
        transferType: "External",
        status: "Completed",
    },
    {
        date: "2024-10-05",
        transactionId: "TRX1005",
        sender: "Isabella Marie Wilson",
        beneficiary: "Benjamin Arthur Davis",
        amount: "$300.00",
        transferType: "Internal",
        status: "Failed",
    },
    {
        date: "2024-10-06",
        transactionId: "TRX1006",
        sender: "Jacob Alexander Walker",
        beneficiary: "Charlotte Elizabeth Scott",
        amount: "$450.00",
        transferType: "External",
        status: "Completed",
    },
    {
        date: "2024-10-07",
        transactionId: "TRX1007",
        sender: "William Patrick Anderson",
        beneficiary: "Amelia Rose Miller",
        amount: "$950.00",
        transferType: "Internal",
        status: "Completed",
    },
    {
        date: "2024-10-08",
        transactionId: "TRX1008",
        sender: "Lucas Ethan Harris",
        beneficiary: "Mia Grace Clark",
        amount: "$600.00",
        transferType: "External",
        status: "Pending",
    },
    {
        date: "2024-10-09",
        transactionId: "TRX1009",
        sender: "Ava Marie Lewis",
        beneficiary: "Daniel Joseph Young",
        amount: "$150.00",
        transferType: "Internal",
        status: "Completed",
    },
    {
        date: "2024-10-10",
        transactionId: "TRX1010",
        sender: "Ethan Michael Nelson",
        beneficiary: "Lily Madison Perez",
        amount: "$400.00",
        transferType: "External",
        status: "Completed",
    }
];