export const transactions = [
    {
      date: "2024-10-01",
      transactionId: "TXN123456",
      fullName: "Alexandra Marie Carter",
      description: "Grocery Store",
      category: "Shopping",
      type: "Debit",
      amount: "$150.75",
      status: "Completed",
    },
    {
      date: "2024-10-03",
      transactionId: "TXN123457",
      fullName: "Benjamin Arthur Kim",
      description: "Electricity Bill",
      category: "Utilities",
      type: "Debit",
      amount: "$75.50",
      status: "Failed",
    },
    {
      date: "2024-10-04",
      transactionId: "TXN123458",
      fullName: "Sophia Grace Nguyen",
      description: "Salary",
      category: "Income",
      type: "Credit",
      amount: "$2500.00",
      status: "Completed",
    },
    {
      date: "2024-10-05",
      transactionId: "TXN123459",
      fullName: "Michael David Lee",
      description: "Dining",
      category: "Food",
      type: "Debit",
      amount: "$45.00",
      status: "Completed",
    },
    {
      date: "2024-10-07",
      transactionId: "TXN123460",
      fullName: "Olivia Rose Patel",
      description: "Gym Membership",
      category: "Health",
      type: "Debit",
      amount: "$60.00",
      status: "Pending",
    },
    {
      date: "2024-10-08",
      transactionId: "TXN123461",
      fullName: "William James O'Connor",
      description: "Freelance Payment",
      category: "Income",
      type: "Credit",
      amount: "$300.00",
      status: "Completed",
    },
    {
      date: "2024-10-09",
      transactionId: "TXN123462",
      fullName: "Isabella Faith Hernandez",
      description: "Online Shopping",
      category: "Shopping",
      type: "Debit",
      amount: "$120.45",
      status: "Completed",
    },
    {
      date: "2024-10-10",
      transactionId: "TXN123463",
      fullName: "Lucas Henry Thompson",
      description: "Water Bill",
      category: "Utilities",
      type: "Debit",
      amount: "$30.00",
      status: "Failed",
    },
    {
      date: "2024-10-12",
      transactionId: "TXN123464",
      fullName: "Emily Claire Brooks",
      description: "Coffee Shop",
      category: "Food",
      type: "Debit",
      amount: "$8.50",
      status: "Completed",
    },
    {
      date: "2024-10-13",
      transactionId: "TXN123465",
      fullName: "Jacob Elijah Morales",
      description: "Gift Received",
      category: "Income",
      type: "Credit",
      amount: "$100.00",
      status: "Completed",
    }
  ];